<?php

namespace Database\Seeders;

use App\Models\LetterField;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class LetterFieldSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $letter_fields = [
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'txtTujuanSurat',
                'txtFieldLabel' => 'Tujuan Surat',
                'txtFieldType' => 'text',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'txtJudulTesis',
                'txtFieldLabel' => 'Judul Tesis',
                'txtFieldType' => 'textarea',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 2,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'fileBuktiPembayaranSPP',
                'txtFieldLabel' => 'Bukti Pembayaran SPP Semester yang sedang berjalan',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 3,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'fileHalamanPengesahan',
                'txtFieldLabel' => 'Halaman pengesahan yang ditanda tangan Ketua Program Studi ( acc penelitian )',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 4,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'fileIzinPenelitian',
                'txtFieldLabel' => 'Format ijin penelitian dari program studi',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 5,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'filePasFoto',
                'txtFieldLabel' => 'Foto 3x4 terbaru',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 6,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 2,
                'txtFieldName' => 'fileBuktiPembayaranSPP',
                'txtFieldLabel' => 'Bukti Pembayaran SPP Semester yang sedang berjalan',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 3,
                'txtFieldName' => 'intIPK',
                'txtFieldLabel' => 'Indeks Prestasi Kumulatif (IPK)',
                'txtFieldType' => 'number',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 3,
                'txtFieldName' => 'dtmYudisium',
                'txtFieldLabel' => 'Tanggal Yudisium',
                'txtFieldType' => 'date',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 3,
                'txtFieldName' => 'fileIjazah',
                'txtFieldLabel' => 'Fotokopi Ijazah',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 3,
                'txtFieldName' => 'fileTranskrip',
                'txtFieldLabel' => 'Transkrip Nilai',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 4,
                'txtFieldName' => 'intIPK',
                'txtFieldLabel' => 'Indeks Prestasi Kumulatif (IPK)',
                'txtFieldType' => 'number',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 4,
                'txtFieldName' => 'dtmYudisium',
                'txtFieldLabel' => 'Tanggal Yudisium',
                'txtFieldType' => 'date',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 4,
                'txtFieldName' => 'fileSKYudisium',
                'txtFieldLabel' => 'Fotokopi SK Yudisium dari Program Studi',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 5,
                'txtFieldName' => 'txtSemester',
                'txtFieldLabel' => 'Semester',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "static", "options": {"1": "1 - Satu (I)", "2": "2 - Dua (II)", "3": "3 - Tiga (III)", "4": "4 - Empat (IV)", "5": "5 - Lima (V)", "6": "6 - Enam (VI)", "7": "7 - Tujuh (VII)", "8": "8 - Delapan (VIII)", "9": "9 - Sembilan (IX)", "10": "10 - Sepuluh (X)", "11": "11 - Sebelas (XI)", "12": "12 - Dua Belas (XII)", "13": "13 - Tiga Belas (XIII)"}}',
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 5,
                'txtFieldName' => 'fileDokumenToefl',
                'txtFieldLabel' => 'Surat Keterangan Aktif Kuliah atau Bukti Pembayaran UKT Semester berjalan',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 2,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 6,
                'txtFieldName' => 'fileSuratPernyataan',
                'txtFieldLabel' => 'Surat Pernyataan tidak sedang menerima Beasiswa dari Sumber Lain (Bermaterai)',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 2,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 6,
                'txtFieldName' => 'fileBuktiPembayaranSPP',
                'txtFieldLabel' => 'Bukti Pembayaran SPP Semester yang sedang berjalan',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 2,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 7,
                'txtFieldName' => 'txtTujuanSurat',
                'txtFieldLabel' => 'Tujuan Surat',
                'txtFieldType' => 'text',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 7,
                'txtFieldName' => 'dtmSelesai',
                'txtFieldLabel' => 'Tanggal Selesai',
                'txtFieldType' => 'date',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 7,
                'txtFieldName' => 'fileSKYudisium',
                'txtFieldLabel' => 'Fotokopi SK Yudisium dari Program Studi',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 7,
                'txtFieldName' => 'fileIjazah',
                'txtFieldLabel' => 'Fotokopi Ijazah',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'txtJenisUjian',
                'txtFieldLabel' => 'Jenis Ujian/Seminar',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "static", "options": {"Seminar Proposal": "Seminar Proposal", "Seminar Hasil": "Seminar Hasil", "Ujian Tesis": "Ujian Tesis"}}',
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'txtJudul',
                'txtFieldLabel' => 'Judul',
                'txtFieldType' => 'textarea',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 2,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'txtKetua',
                'txtFieldLabel' => 'Ketua',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 3,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'txtSekretaris',
                'txtFieldLabel' => 'Sekretaris',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 4,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'txtAnggota',
                'txtFieldLabel' => 'Anggota',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 5,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'txtPembimbing1',
                'txtFieldLabel' => 'Pembimbing 1',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 6,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'txtPembimbing2',
                'txtFieldLabel' => 'Pembimbing 2',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 7,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'filePersetujuanUjian',
                'txtFieldLabel' => 'Surat Persetujuan Ujian/Seminar dari Kaprodi',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 8,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'fileBebasKeuangan',
                'txtFieldLabel' => 'Bebas Keuangan',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 9,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'fileHalamanDepanJurnal',
                'txtFieldLabel' => 'Halaman Depan Jurnal Terpublish',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 10,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'fileTranskripNilai',
                'txtFieldLabel' => 'Transkrip Nilai Terakhir',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 11,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'fileTOEFL',
                'txtFieldLabel' => 'TOEFL',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 12,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'txtHariTanggal',
                'txtFieldLabel' => 'Hari/Tanggal Ujian',
                'txtFieldType' => 'date',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 13,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 1,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'txtJam',
                'txtFieldLabel' => 'Jam',
                'txtFieldType' => 'text',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 14,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 1,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 8,
                'txtFieldName' => 'txtTempat',
                'txtFieldLabel' => 'Tempat Ujian',
                'txtFieldType' => 'text',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 15,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 1,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtJenisUjian',
                'txtFieldLabel' => 'Jenis Ujian/Seminar',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "static", "options": {"Seminar Proposal": "Seminar Proposal", "Seminar Hasil": "Seminar Hasil", "Ujian Tertutup": "Ujian Tertutup", "Ujian Promosi": "Ujian Promosi", "Sidang Komisi Pembimbing": "Sidang Komisi Pembimbing"}}',
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtJudul',
                'txtFieldLabel' => 'Judul',
                'txtFieldType' => 'textarea',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 2,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtKetua',
                'txtFieldLabel' => 'Ketua',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 3,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtSekretaris',
                'txtFieldLabel' => 'Sekretaris',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 4,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtAnggota',
                'txtFieldLabel' => 'Anggota',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 5,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtPembimbing1',
                'txtFieldLabel' => 'Pembimbing 1',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 6,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtPembimbing2',
                'txtFieldLabel' => 'Pembimbing 2',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 7,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtPenguji1',
                'txtFieldLabel' => 'Penguji',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 8,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtPenguji2',
                'txtFieldLabel' => 'Penguji',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 9,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtPenguji3',
                'txtFieldLabel' => 'Penguji',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 10,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtPenguji4',
                'txtFieldLabel' => 'Penguji',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 11,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtPenguji5',
                'txtFieldLabel' => 'Penguji',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 12,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtPengujiKehormatan',
                'txtFieldLabel' => 'Penguji Kehormatan',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "dynamic", "model": "DosenProfile", "with": ["user"], "label": "user.txtFullName", "value": "user.txtFullName"}',
                'bitRequired' => 1,
                'intFieldOrder' => 13,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtPengujiEksternal',
                'txtFieldLabel' => 'Penguji Eksternal',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 14,
                'jsonFieldValidation' => '{"required": false}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'filePersetujuanUjian',
                'txtFieldLabel' => 'Surat Persetujuan Ujian/Seminar dari Kaprodi',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 15,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'fileDokumenToefl',
                'txtFieldLabel' => 'Surat Keterangan Aktif Kuliah atau Bukti Pembayaran UKT Semester berjalan',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 16,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 0,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtHariTanggal',
                'txtFieldLabel' => 'Hari/Tanggal Ujian',
                'txtFieldType' => 'date',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 17,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 1,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtJam',
                'txtFieldLabel' => 'Jam',
                'txtFieldType' => 'text',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 18,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 1,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 9,
                'txtFieldName' => 'txtTempat',
                'txtFieldLabel' => 'Tempat Ujian',
                'txtFieldType' => 'text',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 19,
                'jsonFieldValidation' => '{"required": true}',
                'bitAkademik' => 1,
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
        ];

        foreach ($letter_fields as $field) {
            LetterField::create($field);
        }
    }
}
