<?php

namespace Database\Seeders;

use App\Models\LetterField;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class LetterFieldSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $letter_fields = [
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'txtTujuanSurat',
                'txtFieldLabel' => 'Tujuan Surat',
                'txtFieldType' => 'text',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'txtJudulTesis',
                'txtFieldLabel' => 'Judul Tesis',
                'txtFieldType' => 'textarea',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 2,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'fileBuktiPembayaranSPP',
                'txtFieldLabel' => 'Bukti Pembayaran SPP Semester yang sedang berjalan',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 3,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'fileHalamanPengesahan',
                'txtFieldLabel' => 'Halaman pengesahan yang ditanda tangan Ketua Program Studi ( acc penelitian )',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 4,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'fileIzinPenelitian',
                'txtFieldLabel' => 'Format ijin penelitian dari program studi',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 5,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 1,
                'txtFieldName' => 'filePasFoto',
                'txtFieldLabel' => 'Foto 3x4 terbaru',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 6,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 2,
                'txtFieldName' => 'fileBuktiPembayaranSPP',
                'txtFieldLabel' => 'Bukti Pembayaran SPP Semester yang sedang berjalan',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 3,
                'txtFieldName' => 'intIPK',
                'txtFieldLabel' => 'Indeks Prestasi Kumulatif (IPK)',
                'txtFieldType' => 'number',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 3,
                'txtFieldName' => 'dtmYudisium',
                'txtFieldLabel' => 'Tanggal Yudisium',
                'txtFieldType' => 'date',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 3,
                'txtFieldName' => 'fileIjazah',
                'txtFieldLabel' => 'Fotokopi Ijazah',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 3,
                'txtFieldName' => 'fileTranskrip',
                'txtFieldLabel' => 'Transkrip Nilai',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 4,
                'txtFieldName' => 'intIPK',
                'txtFieldLabel' => 'Indeks Prestasi Kumulatif (IPK)',
                'txtFieldType' => 'number',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 4,
                'txtFieldName' => 'dtmYudisium',
                'txtFieldLabel' => 'Tanggal Yudisium',
                'txtFieldType' => 'date',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 4,
                'txtFieldName' => 'fileSKYudisium',
                'txtFieldLabel' => 'Fotokopi SK Yudisium dari Program Studi',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 5,
                'txtFieldName' => 'txtSemester',
                'txtFieldLabel' => 'Semester',
                'txtFieldType' => 'select',
                'jsonFieldOptions' => '{"source": "static", "options": {"1": "1 - Satu (I)", "2": "2 - Dua (II)", "3": "3 - Tiga (III)", "4": "4 - Empat (IV)", "5": "5 - Lima (V)", "6": "6 - Enam (VI)", "7": "7 - Tujuh (VII)", "8": "8 - Delapan (VIII)", "9": "9 - Sembilan (IX)", "10": "10 - Sepuluh (X)", "11": "11 - Sebelas (XI)", "12": "12 - Dua Belas (XII)", "13": "13 - Tiga Belas (XIII)"}}',
                'bitRequired' => 1,
                'intFieldOrder' => 1,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 5,
                'txtFieldName' => 'fileDokumenToefl',
                'txtFieldLabel' => 'Surat Keterangan Aktif Kuliah atau Bukti Pembayaran UKT Semester berjalan',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 2,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 6,
                'txtFieldName' => 'fileSuratPernyataan',
                'txtFieldLabel' => 'Surat Pernyataan tidak sedang menerima Beasiswa dari Sumber Lain (Bermaterai)',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 2,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ],
            [
                'intLetterType_ID' => 6,
                'txtFieldName' => 'fileBuktiPembayaranSPP',
                'txtFieldLabel' => 'Bukti Pembayaran SPP Semester yang sedang berjalan',
                'txtFieldType' => 'file',
                'jsonFieldOptions' => null,
                'bitRequired' => 1,
                'intFieldOrder' => 2,
                'jsonFieldValidation' => '{"required": true}',
                'bitActive' => 1,
                'txtInsertedBy' => 'Seeder',
                'txtInserted' => now(),
                'txtUpdatedBy' => 'Seeder',
                'txtUpdated' => now(),
            ]
        ];

        foreach ($letter_fields as $field) {
            LetterField::create($field);
        }
    }
}
